# Generated by Django 4.0.3 on 2022-03-23 23:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('responsavel', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='foto_equipamento')),
                ('serial', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('emprestado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.categoria')),
            ],
            options={
                'verbose_name': 'Equipamento',
            },
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestado_anonimo', models.CharField(blank=True, max_length=30, null=True)),
                ('data_emprestimo', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('defeito', models.TextField()),
                ('diagnostico', models.TextField()),
                ('equipamentos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamentos')),
                ('responsavel_empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.empresa')),
            ],
        ),
    ]
