# Generated by Django 4.0.2 on 2022-02-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentos',
            name='teste',
        ),
    ]
