# Generated by Django 4.0.2 on 2022-02-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_remove_equipamentos_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='nome_emprestado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='tempo_duracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
