# Generated by Django 4.0.2 on 2022-02-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_equipamentos_nome_emprestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
