# Generated by Django 4.0.3 on 2022-03-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_emprestimos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='responsavel_empresa',
            new_name='empresa_responsavel',
        ),
    ]
