# Generated by Django 4.0.2 on 2022-02-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0004_alter_equipamentos_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
