# Generated by Django 4.0.3 on 2022-03-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0004_rename_responsavel_empresa_emprestimos_empresa_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='nome_emprestado_anonimo',
            new_name='nome_empresa_anonima',
        ),
    ]
