# Generated by Django 4.0.3 on 2022-03-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0005_rename_nome_emprestado_anonimo_emprestimos_nome_empresa_anonima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='nome_empresa_anonima',
            new_name='empresa_anonima',
        ),
    ]
