# Generated by Django 4.0.3 on 2022-03-03 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_senha'),
        ('equipamento', '0007_categoria_equipamentos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='Usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
