# Generated by Django 4.0.3 on 2022-03-24 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0007_empresa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.empresa'),
        ),
    ]
