# Generated by Django 4.0.3 on 2022-03-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0008_equipamentos_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamentos',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
