# Generated by Django 4.0.3 on 2022-03-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0010_categoria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentos',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='emprestado',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='nome_emprestado',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='tempo_duracao',
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(blank=True, max_length=30)),
                ('data_emprestimo', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('tempo_duracao', models.DateField(blank=True, null=True)),
                ('equipamentos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamentos')),
            ],
        ),
    ]
