# Generated by Django 4.0.3 on 2022-03-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0013_alter_emprestimos_nome_emprestado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'verbose_name': 'Emprestimo'},
        ),
    ]
