# Generated by Django 4.0.3 on 2022-03-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0015_alter_emprestimos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='equipamentos',
            new_name='equipamento',
        ),
    ]
