# Generated by Django 4.0.3 on 2022-03-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0016_rename_equipamentos_emprestimos_equipamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='equipamento',
            new_name='equipamentos',
        ),
    ]
